// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ehaSHr37N1T20VB04g0vuyMWc_5ewb4',
    appId: '1:445959327668:web:0bbd983509a1cad3ff2ce1',
    messagingSenderId: '445959327668',
    projectId: 'flutter-apps-39644',
    authDomain: 'flutter-apps-39644.firebaseapp.com',
    storageBucket: 'flutter-apps-39644.firebasestorage.app',
    measurementId: 'G-8SBP326MJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0orNoYEtTHuegq_xw3xv7LCjbu71Ggn8',
    appId: '1:445959327668:android:d79695313f37d831ff2ce1',
    messagingSenderId: '445959327668',
    projectId: 'flutter-apps-39644',
    storageBucket: 'flutter-apps-39644.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXUL2FYBnYPh4aJvjL8vlO9IUpJZHjAcw',
    appId: '1:445959327668:ios:5020e5dbbb4b62caff2ce1',
    messagingSenderId: '445959327668',
    projectId: 'flutter-apps-39644',
    storageBucket: 'flutter-apps-39644.firebasestorage.app',
    androidClientId: '445959327668-f8kd58hpu7redd7jenalv13daceo6seh.apps.googleusercontent.com',
    iosClientId: '445959327668-bh7sbd885p57b505u2hj4av86mr6snru.apps.googleusercontent.com',
    iosBundleId: 'com.example.sparkpay',
  );
}
